instructions_dict = {
  'physics':[
    "Given the input physics problem, generate a solution that accurately solves it.",
    "Given a physics question, produce an answer that clearly explains the underlying concepts.",
    "For the provided physics scenario, calculate the necessary values to resolve the question.",
    "Given the physics problem description, derive and explain the result comprehensively.",
    "For a stated physics challenge, output a step-by-step solution that covers all aspects of the problem.",
    "Given a physics problem, provide a detailed and precise calculation as the answer.",
    "For the physics question provided, compute and explain the solution in a structured format.",
    "Given a physics problem, produce a clear resolution that includes all necessary computations.",
    "For the described physics issue, offer a complete solution that addresses all variables involved.",
    "Given the input of a physics problem, provide a solution that is both accurate and instructive.",
    "Upon receiving a physics problem, generate a response that clearly solves for the unknowns.",
    "With the presented physics problem, output a comprehensive solution that includes relevant formulas.",
    "Given a general physics query, produce an output that meticulously solves the problem.",
    "For the given physics problem, provide a response that details every step of the solution process.",
    "Given a physics problem, calculate the correct answer and provide a rationale for each step taken.",
    "When presented with a physics problem, output a solution that methodically addresses the challenge.",
    "Given a physics question, develop a response that accurately solves and explains the solution.",
    "For a physics problem provided, offer a thorough explanation and solution in a clear manner.",
    "Upon analyzing a physics problem, generate an answer that effectively solves and explains it.",
    "Given a physics scenario, provide a well-detailed solution that encompasses all necessary calculations."
  ],
  'coding':[
    "Complete the following function based on the provided input code.",
    "Finish coding the function below as per the initial code snippet.",
    "Provide the missing code to fully implement the function shown.",
    "Extend the given function to ensure it performs its intended task.",
    "Fill in the blanks in the function below to complete its functionality.",
    "Write the missing parts of the following function to finalize it.",
    "Conclude the coding of the function below based on its current contents.",
    "Develop the remainder of this function to complete its operation.",
    "Complete the coding task by finishing the function provided.",
    "Add the necessary code to conclude the given function appropriately.",
    "Ensure the given function is fully operational by completing its code.",
    "Finalize the function below by adding the necessary code.",
    "Contribute the missing code to the function below for it to operate correctly.",
    "End the construction of the function below by writing the remaining code.",
    "Supplement the provided function with the needed code to complete it.",
    "Fulfill the coding requirements of the function below by finishing it.",
    "Finish the implementation of the function provided below to make it work.",
    "Write the concluding part of the code for the function shown below.",
    "Provide the concluding code segments for the function presented below.",
    "Complete the programming of the given function by adding the required code."
  ],
  'math':[
    "Calculate the solution to this math equation and state the result.",
    "Find the answer to this mathematical question.",
    "Work out the solution to the following math problem and give your answer.",
    "Determine the solution for this math equation and provide it.",
    "Resolve the following mathematical challenge and provide the solution.",
    "Figure out the answer to this math problem and tell me what it is.",
    "Solve this arithmetic question and record the answer.",
    "Tackle this math equation and submit your solution.",
    "Address this math query and report the solution.",
    "Complete the solution for this math problem and share your answer.",
    "Analyze this math problem, solve it, and give the answer.",
    "Compute the answer to the following mathematical problem.",
    "Work through this math problem and provide the final answer.",
    "Unravel this math question and provide the correct answer.",
    "Process and solve this math problem, then provide the solution.",
    "Conclude this mathematical equation with the correct answer.",
    "Elucidate the solution to this math problem and offer the answer.",
    "Clarify the answer to this mathematical query.",
    "Dissect this math problem, solve it, and provide the solution.",
    "Execute the solution for this math question and record the answer."
],
  'reading':[
    "After reading the following text, answer the primary question it raises.",
    "Carefully read the text below and provide a clear answer to the question posed at the end.",
    "Consider the details in the text and respond accurately to the subsequent question.",
    "Digest the content of the text and give a concise answer to the included question.",
    "Examine the text and provide a well-reasoned answer to the question that follows.",
    "Extract the relevant information from the text to accurately answer the question posed.",
    "From the information given in the text, derive an answer to the following question.",
    "Given the context provided in the text, what is the answer to the ensuing question?",
    "Identify the main point of the text and answer the question based on that understanding.",
    "Interpret the text and apply your understanding to answer the question provided.",
    "Please read the following text and provide an answer to the question at the end.",
    "Read the text below carefully and answer the question based on the information provided.",
    "Review the text and respond to the question based on your interpretation.",
    "Study the text and answer the question that is asked at the end.",
    "Summarize the text and answer the question that follows based on your summary.",
    "Understand the content of the text and provide an answer to the question.",
    "Using the information in the text, what would be your response to the question?",
    "With the information presented in the text, how would you answer the following question?",
    "Analyze the text and answer the question posed directly after.",
    "Interpret the details in the text and provide an answer to the question that follows."
]
}